services:
  sqlserver:
    image:  mcr.microsoft.com/mssql/server:2025-CU3-ubuntu-22.04
    container_name: sqlserver
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: my_view_898
    ports:
      - "1433:1433"
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  sql_data: